[2023-09-13T13:16:20.864+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_elt.save_sensor_data_as_parquet manual__2023-09-13T13:16:09.735573+00:00 [queued]>
[2023-09-13T13:16:20.869+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_elt.save_sensor_data_as_parquet manual__2023-09-13T13:16:09.735573+00:00 [queued]>
[2023-09-13T13:16:20.869+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T13:16:20.877+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): save_sensor_data_as_parquet> on 2023-09-13 13:16:09.735573+00:00
[2023-09-13T13:16:20.880+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2023-09-13T13:16:20.882+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'realtime_elt', 'save_sensor_data_as_parquet', 'manual__2023-09-13T13:16:09.735573+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/realtime_elt.py', '--cfg-path', '/tmp/tmp6jll48lx']
[2023-09-13T13:16:20.884+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask save_sensor_data_as_parquet
[2023-09-13T13:16:20.910+0000] {task_command.py:415} INFO - Running <TaskInstance: realtime_elt.save_sensor_data_as_parquet manual__2023-09-13T13:16:09.735573+00:00 [running]> on host 6908241070e1
[2023-09-13T13:16:20.959+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_elt' AIRFLOW_CTX_TASK_ID='save_sensor_data_as_parquet' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T13:16:09.735573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T13:16:09.735573+00:00'
[2023-09-13T13:16:20.960+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/realtime_elt.py", line 50, in save_sensor_data_as_parquet
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/sensors_realtime.json'
[2023-09-13T13:16:20.966+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=realtime_elt, task_id=save_sensor_data_as_parquet, execution_date=20230913T131609, start_date=20230913T131620, end_date=20230913T131620
[2023-09-13T13:16:20.973+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task save_sensor_data_as_parquet ([Errno 2] No such file or directory: '/opt/airflow/data/sensors_realtime.json'; 201)
[2023-09-13T13:16:21.014+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T13:16:21.026+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
