[2023-09-13T12:37:41.637+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T12:37:40.539910+00:00 [queued]>
[2023-09-13T12:37:41.642+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T12:37:40.539910+00:00 [queued]>
[2023-09-13T12:37:41.643+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T12:37:41.650+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): upload_file_to_s3> on 2023-09-13 12:37:40.539910+00:00
[2023-09-13T12:37:41.653+0000] {standard_task_runner.py:57} INFO - Started process 426 to run task
[2023-09-13T12:37:41.655+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'realtime_elt', 'upload_file_to_s3', 'manual__2023-09-13T12:37:40.539910+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/realtime_elt.py', '--cfg-path', '/tmp/tmpj4ciseww']
[2023-09-13T12:37:41.656+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask upload_file_to_s3
[2023-09-13T12:37:41.686+0000] {task_command.py:415} INFO - Running <TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T12:37:40.539910+00:00 [running]> on host 0baba5155cab
[2023-09-13T12:37:41.740+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_elt' AIRFLOW_CTX_TASK_ID='upload_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T12:37:40.539910+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T12:37:40.539910+00:00'
[2023-09-13T12:37:41.741+0000] {logging_mixin.py:151} INFO - OrderedDict()
[2023-09-13T12:37:42.043+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/realtime_elt.py", line 86, in upload_file_to_s3
    aws_access_key_id=config["access_key"],
KeyError: 'access_key'
[2023-09-13T12:37:42.051+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=realtime_elt, task_id=upload_file_to_s3, execution_date=20230913T123740, start_date=20230913T123741, end_date=20230913T123742
[2023-09-13T12:37:42.061+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task upload_file_to_s3 ('access_key'; 426)
[2023-09-13T12:37:42.108+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T12:37:42.123+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
