[2023-09-13T13:07:19.247+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T13:07:17.867413+00:00 [queued]>
[2023-09-13T13:07:19.252+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T13:07:17.867413+00:00 [queued]>
[2023-09-13T13:07:19.252+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-13T13:07:19.259+0000] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): upload_file_to_s3> on 2023-09-13 13:07:17.867413+00:00
[2023-09-13T13:07:19.262+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2023-09-13T13:07:19.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'realtime_elt', 'upload_file_to_s3', 'manual__2023-09-13T13:07:17.867413+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/realtime_elt.py', '--cfg-path', '/tmp/tmppq6edf64']
[2023-09-13T13:07:19.266+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask upload_file_to_s3
[2023-09-13T13:07:19.294+0000] {task_command.py:415} INFO - Running <TaskInstance: realtime_elt.upload_file_to_s3 manual__2023-09-13T13:07:17.867413+00:00 [running]> on host 1186b8b85817
[2023-09-13T13:07:19.353+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='realtime_elt' AIRFLOW_CTX_TASK_ID='upload_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-09-13T13:07:17.867413+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-13T13:07:17.867413+00:00'
[2023-09-13T13:07:19.354+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/realtime_elt.py", line 84, in upload_file_to_s3
    for line in f.readlines:
TypeError: 'builtin_function_or_method' object is not iterable
[2023-09-13T13:07:19.360+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=realtime_elt, task_id=upload_file_to_s3, execution_date=20230913T130717, start_date=20230913T130719, end_date=20230913T130719
[2023-09-13T13:07:19.368+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task upload_file_to_s3 ('builtin_function_or_method' object is not iterable; 314)
[2023-09-13T13:07:19.395+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-13T13:07:19.409+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
